### ISSUE TITLE
"useLocation() may be used only in the context of a component."

### ISSUE THREAD

**Issue by nundys** [awslabs/aws-codesuite-plugins-for-backstage#11]
"useLocation() may be used only in the context of a component." Error.  Any thoughts?

![image](https://user-images.githubusercontent.com/367561/205862165-9239ab56-ab08-49dd-a8e8-a82c847c5180.png)

**Comment by nimakaviani** [comment]
interesting! thanks for the report. W

We will try to test things on our end too and keep this thread updated.

**Comment by nundys** [comment]
Sorry, I had some local configuration issues that might have generate the afore-mentioned build issues, so I thought it best to delete that particular bug-report.  Now, under new config on a M1Pro Mac, it seems to be building.   However, at run-time, I am getting the "useLocation() may be used only in the context of a component." error as reported above.  I'd be grateful for your help in debugging it, the best I can find on the Internet is [this](https://github.com/remix-run/react-router/issues/8518)

**Comment by niallthomson** [comment]
@nundys we've just merged a re-architecture of the plugins to better serve us going forwards. Can you confirm if this issue is still occurring?
