### ISSUE TITLE
CodePipeline link incorrect in CodePipelineOverviewCard

### ISSUE THREAD

**Issue by darrenlewisexperian** [awslabs/aws-codesuite-plugins-for-backstage#54]
The URL for the CodePipeline link to the AWS console in the `CodePipelineOverviewCard` is incorrectly using a CodeBuild URL format which results in a 404 e.g. https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/{accountId}/projects/{pipelineName}/?region=eu-west-1.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/80396286/216459070-1a49f4a4-6b61-4296-ae2d-37f133e31c64.png">

I think this is the offending line https://github.com/awslabs/aws-codesuite-plugins-for-backstage/blob/main/plugins/aws-codesuite/src/components/CodePipelineWidget/CodePipelineWidget.tsx#L80.

**Comment by niallthomson** [comment]
Hi @darrenlewisexperian thanks for reporting this. Working on a fix.

**Comment by darrenlewisexperian** [comment]
Appreciate the quick turnaround @niallthomson 👍
