### ISSUE TITLE
CodeBuild build number link incorrect

### ISSUE THREAD

**Issue by darrenlewisexperian** [awslabs/aws-codesuite-plugins-for-backstage#55]
The CodeBuild build number link is incorrect. The CodeBuild ID field appears to have the project name in twice e.g. `projectName:projectName:ID` instead of just `projectName:ID`.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/80396286/216464112-06766f6e-ba77-4417-90b7-d18d9cf6c7b7.png">

Not sure where the specific problem is on this one. The URL format looks correct in https://github.com/awslabs/aws-codesuite-plugins-for-backstage/blob/main/plugins/aws-codesuite/src/components/CodeBuildBuildsTable/CodeBuildBuildsTable.tsx#L35, so not sure if it's the backend or something else?

**Comment by niallthomson** [comment]
Hi @darrenlewisexperian thanks for reporting this. Working on a fix.

**Comment by darrenlewisexperian** [comment]
Appreciate the quick turnaround 👍

**Comment by darrenlewisexperian** [comment]
Appreciate the quick turnaround @niallthomson 👍
