### ISSUE TITLE
Add to the Backstage plugin marketplace

### ISSUE THREAD

**Issue by OrkoHunter** [awslabs/aws-codesuite-plugins-for-backstage#6]
Hey folks!

Really awesome work on adding to the list of Backstage plugins for CI/CD integrations. If I can poke, can you please add it to the https://backstage.io/plugins marketplace as well? It's a place where Adopters come to discover existing plugins for Backstage. [Docs on how to add to the list](https://backstage.io/docs/plugins/add-to-marketplace).

**Comment by nimakaviani** [comment]
thanks for the note!

yes, definitely on our roadmap. will be listed there soon! will keep this thread updated when that happens.

**Comment by anshulgargamway** [comment]
Any update on getting this plugin published to backstage

**Comment by niallthomson** [comment]
@anshulgargamway we are working on publishing NPM packages for the plugins and then will be able to work through getting added to the marketplace.

**Comment by anshulgargamway** [comment]
@niallthomson : Thanks for the response just want to know until when the NPM packages for plugins will be available ?

**Comment by nimakaviani** [comment]
Hopefully within the next month or so. We need to do extra security audits and collect internal approvals before publishing the NPM package. we will keep this threaded updated as soon as it happens.

**Comment by anshulgargamway** [comment]
@nimakaviani : Any further updates on same.

**Comment by nundys** [comment]
+1

**Comment by niallthomson** [comment]
Completed https://github.com/backstage/backstage/pull/15814
